export type PricingLanguage = "en" | "bg";

export const pricingCopy = {
  en: {
    brandTagline: "Everything important in one place",
    backToDashboard: "Back to dashboard",
    eyebrow: "WEBVAULT PLANS",
    title: "More space. Full control.",
    description: "Start free, then unlock PRO when WebVault becomes part of your daily routine.",
    nativeNotice: "Subscriptions aren't available for purchase in this iOS app yet. Your existing PRO status will keep syncing.",
    checkoutCancelled: "Payment was cancelled. You can choose a plan whenever you're ready.",
    proActivated: "PRO is active. All premium features are unlocked.",
    paymentAccepted: "Payment accepted. If PRO doesn't appear yet, refresh in a few seconds.",
    confirmingPayment: "Confirming your payment and activating PRO…",
    mobileCheckoutUnavailable: "Subscription purchases in the mobile app will be added with native in-app billing. Until then, any active PRO status will keep syncing automatically.",
    signInRequired: "Sign in to WebVault to activate PRO.",
    missingStripePrice: "Stripe price IDs are missing. Check NEXT_PUBLIC_STRIPE_PRICE_MONTHLY and NEXT_PUBLIC_STRIPE_PRICE_YEARLY.",
    checkoutFailed: "We couldn't open Stripe Checkout.",
    portalUnavailable: "Subscription management will be added with native in-app billing.",
    portalFailed: "We couldn't open subscription management.",
    profileLoadFailed: "We couldn't load your subscription status. Refresh the page and try again.",
    proActive: "PRO is active",
    nativeProDescription: "Your subscription is synced with WebVault. Subscription management in the app will be available with native in-app billing.",
    stripeProDescription: "Manage payment methods, invoices or cancel your subscription in the Stripe Customer Portal.",
    manageSubscription: "Manage subscription",
    comparisonAriaLabel: "Plan comparison",
    feature: "Feature",
    sites: "Sites",
    categories: "Categories",
    devices: "Devices",
    deviceSync: "Sync across devices",
    backup: "Backup / Export / Import",
    customIcons: "Custom icons and colours",
    pwaInstall: "PWA installation",
    prioritySupport: "Priority support",
    freePlan: "FREE",
    proPlan: "PRO",
    startingAt: "from €3.99",
    upTo: "Up to",
    withinLimit: "Within the limit",
    unlimited: "Unlimited",
    monthlyPlan: "Monthly plan",
    yearlyPlan: "Yearly plan",
    perMonth: "per month",
    perYear: "per year · save €18.88",
    bestValue: "BEST VALUE",
    flexible: "FLEXIBLE",
    mobileComingSoon: "Coming soon in the app",
    proAlreadyActive: "PRO is active",
    signInToActivate: "Sign in to activate",
    choosePlan: "Choose plan",
    paymentFooter: "Payments are securely processed by Stripe. You can manage or cancel your subscription at any time in the Customer Portal.",
  },
  bg: {
    brandTagline: "Всичко важно на едно място",
    backToDashboard: "Към таблото",
    eyebrow: "ПЛАНОВЕ ЗА WEBVAULT",
    title: "Повече място. Пълен контрол.",
    description: "Започни безплатно, а когато WebVault стане твоето ежедневие — отключи PRO.",
    nativeNotice: "В тази iOS версия покупките не се извършват през външен Stripe Checkout. PRO статусът от вече активен план се показва и синхронизира нормално.",
    checkoutCancelled: "Плащането беше отменено. Можеш да избереш план, когато си готов.",
    proActivated: "PRO е активиран. Всички premium функции са отключени.",
    paymentAccepted: "Плащането е прието. Ако PRO още не се вижда, обнови след няколко секунди.",
    confirmingPayment: "Потвърждаваме плащането ти и активираме PRO…",
    mobileCheckoutUnavailable: "Абонаментът в мобилното приложение ще бъде добавен с native in-app billing. Дотогава PRO статусът ти се синхронизира автоматично, ако вече имаш активен план.",
    signInRequired: "Влез в WebVault, за да активираш PRO.",
    missingStripePrice: "Липсва Stripe price ID. Провери NEXT_PUBLIC_STRIPE_PRICE_MONTHLY и NEXT_PUBLIC_STRIPE_PRICE_YEARLY.",
    checkoutFailed: "Не успяхме да отворим Stripe Checkout.",
    portalUnavailable: "Управлението на абонаментите ще бъде добавено с native in-app billing.",
    portalFailed: "Не успяхме да отворим управлението на абонамента.",
    profileLoadFailed: "Не успяхме да заредим статуса на абонамента. Обнови страницата и опитай отново.",
    proActive: "PRO е активен",
    nativeProDescription: "Абонаментът ти е синхронизиран с WebVault. Управлението от приложението ще бъде налично с native in-app billing.",
    stripeProDescription: "Управлявай начина на плащане, фактурите или отказа от абонамента в Stripe Customer Portal.",
    manageSubscription: "Управлявай абонамента",
    comparisonAriaLabel: "Сравнение на планове",
    feature: "Функция",
    sites: "Сайтове",
    categories: "Категории",
    devices: "Устройства",
    deviceSync: "Синхронизация между устройства",
    backup: "Backup / Export / Import",
    customIcons: "Персонални икони и цветове",
    pwaInstall: "Инсталиране като приложение",
    prioritySupport: "Приоритетна поддръжка",
    freePlan: "FREE",
    proPlan: "PRO",
    startingAt: "от 3.99€",
    upTo: "До",
    withinLimit: "В рамките на лимита",
    unlimited: "Неограничено",
    monthlyPlan: "Месечен план",
    yearlyPlan: "Годишен план",
    perMonth: "на месец",
    perYear: "на година · спестяваш 18.88€",
    bestValue: "НАЙ-ДОБРА СТОЙНОСТ",
    flexible: "ГЪВКАВО",
    mobileComingSoon: "Скоро в приложението",
    proAlreadyActive: "PRO е активен",
    signInToActivate: "Влез, за да активираш",
    choosePlan: "Избери план",
    paymentFooter: "Плащането се обработва сигурно от Stripe. Можеш да управляваш или откажеш абонамента по всяко време от Customer Portal.",
  },
} as const satisfies Record<PricingLanguage, Record<string, string>>;

export function getPricingCopy(language: PricingLanguage) {
  return pricingCopy[language];
}
